# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8687e8ab6cac738d0226061cd99fd8e23a7116d221a068f33a6b11496eef81a86bd1546df60eb34e0438d5d1b4f04012c356b3f51181274a6d6b8cb01d2ea04b

test:
  secret_key_base: 0f85b9b6212c53316ad30503e3cbd2a1d297434857f554899a531418e755a10ab4e55703c8ff6954e16cec94e1c485871744d5814d5a1cff7d4c5c6369e049e7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
